# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 18, size: 0.0385, name: tag_18},
    {id: 19, size: 0.0385, name: tag_19},
    {id: 20, size: 0.0385, name: tag_20},
    {id: 21, size: 0.0385, name: tag_21},
    {id: 22, size: 0.0385, name: tag_22},
    {id: 23, size: 0.0385, name: tag_23},
    {id: 24, size: 0.0385, name: tag_24},
    {id: 25, size: 0.0385, name: tag_25},
    {id: 26, size: 0.0385, name: tag_26},
    {id: 27, size: 0.0385, name: tag_27},
    {id: 28, size: 0.0385, name: tag_28},
    {id: 29, size: 0.0385, name: tag_29},
    {id: 30, size: 0.0385, name: tag_30},
    {id: 31, size: 0.0385, name: tag_31}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: "map",
      layout:
      [
        {
          id: 0     , size: 0.0385,
           x: 0.000000,  y: 0.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 1     , size: 0.0385,
           x: 0.000000,  y: 1.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 2     , size: 0.0385,
           x: 0.000000,  y: 2.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 3     , size: 0.0385,
           x: 0.000000,  y: 3.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 4     , size: 0.0385,
           x: 0.000000,  y: 4.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 5     , size: 0.0385,
           x: 0.000000,  y: 5.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 6     , size: 0.0385,
           x: 1.000000,  y: 0.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 7     , size: 0.0385,
           x: 1.000000,  y: 1.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 8     , size: 0.0385,
           x: 1.000000,  y: 2.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 9     , size: 0.0385,
           x: 1.000000,  y: 3.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 10    , size: 0.0385,
           x: 1.000000,  y: 4.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 11    , size: 0.0385,
           x: 1.000000,  y: 5.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 12    , size: 0.0385,
           x: 2.000000,  y: 0.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 13    , size: 0.0385,
           x: 2.000000,  y: 1.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 14    , size: 0.0385,
           x: 2.000000,  y: 2.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 15    , size: 0.0385,
           x: 2.000000,  y: 3.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 16    , size: 0.0385,
           x: 2.000000,  y: 4.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        },
        {
          id: 17    , size: 0.0385,
           x: 2.000000,  y: 5.000000,  z: 0.000000,
          qw: 0.707107, qx: 0.000000, qy: 0.000000, qz: -0.707107
        }
      ]
    }
  ]
